# Generated by Django 2.2 on 2019-05-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookticket', '0002_auto_20190428_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
