# Generated by Django 2.2 on 2019-05-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookticket', '0002_auto_20190519_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adress', models.GenericIPAddressField()),
                ('url', models.CharField(max_length=250)),
                ('resp_status', models.CharField(max_length=250)),
            ],
        ),
    ]
