# Generated by Django 2.2 on 2019-05-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookticket', '0003_clientrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='resp_status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
