# Generated by Django 2.2 on 2019-05-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookticket', '0003_auto_20190501_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='languages',
            field=models.ManyToManyField(to='bookticket.Language'),
        ),
    ]
