# Generated by Django 2.2 on 2019-05-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookticket', '0004_auto_20190501_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='twod',
            field=models.BooleanField(default=False),
        ),
    ]
