# Generated by Django 2.2 on 2019-05-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookticket', '0004_auto_20190519_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='is_movie',
            field=models.BooleanField(default=False),
        ),
    ]
