# Generated by Django 2.2 on 2019-05-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookticket', '0005_movie_twod'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='threed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='twod',
            field=models.BooleanField(default=True),
        ),
    ]
