# Generated by Django 2.2 on 2019-05-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookticket', '0009_auto_20190511_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
