# Generated by Django 2.2 on 2019-05-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookticket', '0010_theater_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
